
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.cresb49.server.AnalizadorJava;

/** CUP generated class containing symbol constants. */
public class ParserJavaSym {
  /* terminals */
  public static final int DOSPUNTOS = 48;
  public static final int CHAR = 12;
  public static final int STR = 11;
  public static final int ENTERO = 24;
  public static final int LLA_C = 45;
  public static final int CASE = 21;
  public static final int DIFERENTE = 25;
  public static final int DOUBLE = 13;
  public static final int LLA_A = 44;
  public static final int SUMAR = 34;
  public static final int PRIVATE = 4;
  public static final int INT = 9;
  public static final int PUNTOCOMA = 49;
  public static final int FOR = 17;
  public static final int NOT = 33;
  public static final int AND = 31;
  public static final int IGUAL = 26;
  public static final int OR = 32;
  public static final int BOOL = 10;
  public static final int CLASS = 51;
  public static final int DIV = 37;
  public static final int IF = 15;
  public static final int ID = 22;
  public static final int EOF = 0;
  public static final int DECIMAL = 23;
  public static final int RETURN = 8;
  public static final int EQUAL = 52;
  public static final int TRUE = 53;
  public static final int error = 1;
  public static final int OBJ = 14;
  public static final int COMA = 47;
  public static final int MUL = 36;
  public static final int MENOS = 39;
  public static final int MAYOR_QUE = 30;
  public static final int PA_C = 41;
  public static final int BREAK = 7;
  public static final int PA_A = 40;
  public static final int CO_C = 43;
  public static final int SWITCH = 20;
  public static final int IMPORT = 2;
  public static final int CO_A = 42;
  public static final int RESTAR = 35;
  public static final int ELSE = 16;
  public static final int PUNTO = 46;
  public static final int PROTECTED = 5;
  public static final int FINAL = 6;
  public static final int WHILE = 19;
  public static final int MAYOR_IGUAL = 28;
  public static final int PUBLIC = 3;
  public static final int STRING = 50;
  public static final int MENOR_QUE = 29;
  public static final int MENOR_IGUAL = 27;
  public static final int FALSE = 54;
  public static final int DO = 18;
  public static final int MAS = 38;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IMPORT",
  "PUBLIC",
  "PRIVATE",
  "PROTECTED",
  "FINAL",
  "BREAK",
  "RETURN",
  "INT",
  "BOOL",
  "STR",
  "CHAR",
  "DOUBLE",
  "OBJ",
  "IF",
  "ELSE",
  "FOR",
  "DO",
  "WHILE",
  "SWITCH",
  "CASE",
  "ID",
  "DECIMAL",
  "ENTERO",
  "DIFERENTE",
  "IGUAL",
  "MENOR_IGUAL",
  "MAYOR_IGUAL",
  "MENOR_QUE",
  "MAYOR_QUE",
  "AND",
  "OR",
  "NOT",
  "SUMAR",
  "RESTAR",
  "MUL",
  "DIV",
  "MAS",
  "MENOS",
  "PA_A",
  "PA_C",
  "CO_A",
  "CO_C",
  "LLA_A",
  "LLA_C",
  "PUNTO",
  "COMA",
  "DOSPUNTOS",
  "PUNTOCOMA",
  "STRING",
  "CLASS",
  "EQUAL",
  "TRUE",
  "FALSE"
  };
}

