
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.cresb49.appcliente.analizadores.filecopy;

import java.util.ArrayList;
import com.cresb49.appcliente.analizadores.ErrorAnalisis;
import com.cresb49.appcliente.analizadores.Token;
import com.cresb49.appcliente.ED.Pila;
import com.cresb49.appcliente.analizadores.filecopy.obj.*;
import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class ParserFileCopy extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return ParserFileCopySym.class;
}

  /** Default constructor. */
  @Deprecated
  public ParserFileCopy() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public ParserFileCopy(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserFileCopy(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\013\000\002\002\005\000\002\002\004\000\002\003" +
    "\006\000\002\003\006\000\002\003\006\000\002\003\006" +
    "\000\002\004\007\000\002\004\007\000\002\004\007\000" +
    "\002\004\007\000\002\004\002" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\027\000\004\004\005\001\002\000\004\002\031\001" +
    "\002\000\012\011\ufff7\012\ufff7\013\ufff7\014\ufff7\001\002" +
    "\000\012\011\012\012\011\013\013\014\014\001\002\000" +
    "\004\005\010\001\002\000\004\002\001\001\002\000\004" +
    "\007\026\001\002\000\004\007\023\001\002\000\004\007" +
    "\020\001\002\000\004\007\015\001\002\000\004\010\016" +
    "\001\002\000\006\005\ufffc\006\017\001\002\000\012\011" +
    "\ufff8\012\ufff8\013\ufff8\014\ufff8\001\002\000\004\010\021" +
    "\001\002\000\006\005\ufffd\006\022\001\002\000\012\011" +
    "\ufff9\012\ufff9\013\ufff9\014\ufff9\001\002\000\004\010\024" +
    "\001\002\000\006\005\uffff\006\025\001\002\000\012\011" +
    "\ufffb\012\ufffb\013\ufffb\014\ufffb\001\002\000\004\010\027" +
    "\001\002\000\006\005\ufffe\006\030\001\002\000\012\011" +
    "\ufffa\012\ufffa\013\ufffa\014\ufffa\001\002\000\004\002\000" +
    "\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\027\000\004\002\003\001\001\000\002\001\001\000" +
    "\006\003\006\004\005\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserFileCopy$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserFileCopy$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserFileCopy$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    // Connect this parser to a scanner!

    private static final String ERROR_TYPE_SIN = "Sintactico";
    private static final String ERROR_TYPE_SEM = "Semantico";

    private LexerFileCopy lexerFileCopy;
    private ArrayList<ErrorAnalisis> errorAnalisisesTmp;
    private SimbolosTerminalesFileCopy simbolosTerminalesFileCopy;

    
    public ParserFileCopy (LexerFileCopy lexerFileCopy){ 
        super(lexerFileCopy);
        this.lexerFileCopy=lexerFileCopy;
        this.simbolosTerminalesFileCopy = new SimbolosTerminalesFileCopy();
    }

    public void report_error(String message, Object info) {
        System.out.println("public void report_error");
    }
    
    public void report_fatal_error(String message, Object info) {
        System.out.println("public void report_fatal_error");
    }

    public void syntax_error(Symbol cur_token) {
        Token tok = (Token) cur_token.value;
        if(tok!=null){
            if (cur_token.sym == ParserFileCopySym.EOF) {
                String er = "Simbolo inesperado, se esperaba: "+ simbolosTerminalesFileCopy.obtenerSimbolos(expected_token_ids()).toString();
                System.out.println("FIN ARCHIVO"+" "+er);
                this.lexerFileCopy.getErrors().push(new ErrorAnalisis(ERROR_TYPE_SIN,"FIN ARCHIVO", cur_token.left, cur_token.right, er));
                System.out.println(er);
            } else {
                String er = "Simbolo inesperado, se esperaba: "+ simbolosTerminalesFileCopy.obtenerSimbolos(expected_token_ids()).toString();
                System.out.println(tok.getLexema()+" "+er);
                this.lexerFileCopy.getErrors().push(new ErrorAnalisis(ERROR_TYPE_SIN,tok.getLexema(), tok.getLinea(), tok.getColumna(), er));
                System.out.println(er);
            }
        }else{
            String er = "Simbolo inesperado, se esperaba: "+ simbolosTerminalesFileCopy.obtenerSimbolos(expected_token_ids()).toString();
            System.out.println("FIN ARCHIVO"+" "+er);
            this.lexerFileCopy.getErrors().push(new ErrorAnalisis(ERROR_TYPE_SIN,"FIN ARCHIVO", cur_token.left, cur_token.right, er));
            System.out.println(er);
        }
    }

    public void unrecovered_syntax_error(Symbol cur_token) {
        if (cur_token.sym == ParserFileCopySym.EOF) {
            String er = "Error irrecuperable se llego al final del archivo";
            System.out.println("FIN ARCHIVO"+" "+er);
            this.lexerFileCopy.getErrors().push(new ErrorAnalisis(ERROR_TYPE_SIN,"FIN ARCHIVO", cur_token.left, cur_token.right, er));
            System.out.println(er);
        } else {
            Token tok = (Token) cur_token.value;
            //String er = "Error irrecuperable, un posible simbolo esperado: "+ simbolosTerminalesFileCopy.obtenerSimbolos(expected_token_ids()).toString();
            String er = "Error irrecuperable resuelva el error anterior";
            System.out.println(tok.getLexema()+" "+er);
            this.lexerFileCopy.getErrors().push(new ErrorAnalisis(ERROR_TYPE_SIN, tok.getLexema(), tok.getLinea(), tok.getColumna(), er));
            System.out.println(er);
        }
    }

    private void semantic_error(Token token,String contexto) {
        this.lexerFileCopy.getErrors().push(new ErrorAnalisis(ERROR_TYPE_SEM,token.getLexema(), token.getLinea(), token.getColumna(), contexto));
    }

    private boolean definition_error(Token ini,Token fin,ArrayList<String> errores){
        boolean status = false;
        for (String errore : errores) {
            status = true;
            String error = "Error en definicion, "+errore+" Ubicacion general --> Linea: "+ini.getLinea()+" a Linea: "+fin.getLinea();
            this.lexerFileCopy.getErrors().push(new ErrorAnalisis(ERROR_TYPE_SEM, ini.getLexema(), ini.getLinea(), ini.getColumna(), error));
            System.out.println(error);
        }
        return status;
    }

    private void referencia_numerica_incorrecta(Token token,Double valor){
        this.lexerFileCopy.getErrors().push(new ErrorAnalisis(ERROR_TYPE_SIN,valor.toString(), token.getLinea(),(token.getColumna()+1), ", Se espera un valor entero o una operacion con resultado entero"));
    }

    private void referencia_numero_negativo(Token token,Double valor){
        this.lexerFileCopy.getErrors().push(new ErrorAnalisis(ERROR_TYPE_SEM,String.valueOf(valor.intValue()), token.getLinea(),(token.getColumna()+1), ", Se esperaba un valor positivo"));
    }

    private void referencia_numero_negativo_values(Token token,Double valor){
        this.lexerFileCopy.getErrors().push(new ErrorAnalisis(ERROR_TYPE_SEM,valor.toString(), token.getLinea(),(token.getColumna()+1), ",Se espera un valor positivo o una operacion con resultado positivo"));
    }

    protected int error_sync_size() {
		return 1;
	}


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$ParserFileCopy$actions {
  private final ParserFileCopy parser;

  /** Constructor */
  CUP$ParserFileCopy$actions(ParserFileCopy parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ParserFileCopy$do_action_part00000000(
    int                        CUP$ParserFileCopy$act_num,
    java_cup.runtime.lr_parser CUP$ParserFileCopy$parser,
    java.util.Stack            CUP$ParserFileCopy$stack,
    int                        CUP$ParserFileCopy$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserFileCopy$result;

      /* select the action based on the action number */
      switch (CUP$ParserFileCopy$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // ini ::= LLA_A copy LLA_C 
            {
              Object RESULT =null;
		int coppleft = ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-1)).left;
		int coppright = ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-1)).right;
		FileCopy copp = (FileCopy)((java_cup.runtime.Symbol) CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-1)).value;
		
                                    RESULT=copp;
                                    if(RESULT!=null){
                                        System.out.println(RESULT.toString());
                                    }
                                
              CUP$ParserFileCopy$result = parser.getSymbolFactory().newSymbol("ini",0, ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-2)), ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.peek()), RESULT);
            }
          return CUP$ParserFileCopy$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= ini EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-1)).value;
		RESULT = start_val;
              CUP$ParserFileCopy$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-1)), ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserFileCopy$parser.done_parsing();
          return CUP$ParserFileCopy$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // copy ::= copyp PROYECT1 DOSPUNTOS STRING 
            {
              FileCopy RESULT =null;
		int coppleft = ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-3)).left;
		int coppright = ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-3)).right;
		FileCopy copp = (FileCopy)((java_cup.runtime.Symbol) CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-3)).value;
		int strleft = ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.peek()).left;
		int strright = ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.peek()).right;
		Object str = (Object)((java_cup.runtime.Symbol) CUP$ParserFileCopy$stack.peek()).value;
		
                                                                RESULT = copp;
                                                                if(RESULT != null){
                                                                    Token token = (Token) str;
                                                                    if(RESULT.getPathProyecto1()!=null){
                                                                        System.out.println("La propeidad JSON ya estaba definida");
                                                                    }else{
                                                                        if(token.getLexema().isEmpty() || token.getLexema().isBlank()){
                                                                            System.out.println("La cadena de asigancion esta vacia");
                                                                        }else{
                                                                            RESULT.setPathProyecto1(token.getLexema());
                                                                        }
                                                                    }
                                                                }
                                                            
              CUP$ParserFileCopy$result = parser.getSymbolFactory().newSymbol("copy",1, ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-3)), ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.peek()), RESULT);
            }
          return CUP$ParserFileCopy$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // copy ::= copyp PROYECT2 DOSPUNTOS STRING 
            {
              FileCopy RESULT =null;
		int coppleft = ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-3)).left;
		int coppright = ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-3)).right;
		FileCopy copp = (FileCopy)((java_cup.runtime.Symbol) CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-3)).value;
		int strleft = ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.peek()).left;
		int strright = ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.peek()).right;
		Object str = (Object)((java_cup.runtime.Symbol) CUP$ParserFileCopy$stack.peek()).value;
		
                                                                RESULT = copp;
                                                                if(RESULT != null){
                                                                    Token token = (Token) str;
                                                                    if(RESULT.getPathProyecto2()!=null){
                                                                        System.out.println("La propeidad JSON ya estaba definida");
                                                                    }else{
                                                                        if(token.getLexema().isEmpty() || token.getLexema().isBlank()){
                                                                            System.out.println("La cadena de asigancion esta vacia");
                                                                        }else{
                                                                            RESULT.setPathProyecto2(token.getLexema());
                                                                        }
                                                                    }
                                                                }
                                                            
              CUP$ParserFileCopy$result = parser.getSymbolFactory().newSymbol("copy",1, ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-3)), ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.peek()), RESULT);
            }
          return CUP$ParserFileCopy$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // copy ::= copyp FILEDEF DOSPUNTOS STRING 
            {
              FileCopy RESULT =null;
		int coppleft = ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-3)).left;
		int coppright = ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-3)).right;
		FileCopy copp = (FileCopy)((java_cup.runtime.Symbol) CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-3)).value;
		int strleft = ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.peek()).left;
		int strright = ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.peek()).right;
		Object str = (Object)((java_cup.runtime.Symbol) CUP$ParserFileCopy$stack.peek()).value;
		
                                                                RESULT = copp;
                                                                if(RESULT != null){
                                                                    Token token = (Token) str;
                                                                    if(RESULT.getPathFileDef()!=null){
                                                                        System.out.println("La propeidad JSON ya estaba definida");
                                                                    }else{
                                                                        if(token.getLexema().isEmpty() || token.getLexema().isBlank()){
                                                                            System.out.println("La cadena de asigancion esta vacia");
                                                                        }else{
                                                                            RESULT.setPathFileDef(token.getLexema());
                                                                        }
                                                                    }
                                                                }
                                                            
              CUP$ParserFileCopy$result = parser.getSymbolFactory().newSymbol("copy",1, ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-3)), ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.peek()), RESULT);
            }
          return CUP$ParserFileCopy$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // copy ::= copyp REPORTJSON DOSPUNTOS STRING 
            {
              FileCopy RESULT =null;
		int coppleft = ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-3)).left;
		int coppright = ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-3)).right;
		FileCopy copp = (FileCopy)((java_cup.runtime.Symbol) CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-3)).value;
		int strleft = ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.peek()).left;
		int strright = ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.peek()).right;
		Object str = (Object)((java_cup.runtime.Symbol) CUP$ParserFileCopy$stack.peek()).value;
		
                                                                RESULT = copp;
                                                                if(RESULT != null){
                                                                    Token token = (Token) str;
                                                                    if(RESULT.getPathFileReporteJson()!=null){
                                                                        System.out.println("La propeidad JSON ya estaba definida");
                                                                    }else{
                                                                        if(token.getLexema().isEmpty() || token.getLexema().isBlank()){
                                                                            System.out.println("La cadena de asigancion esta vacia");
                                                                        }else{
                                                                            RESULT.setPathFileReporteJson(token.getLexema());
                                                                        }
                                                                    }
                                                                }
                                                            
              CUP$ParserFileCopy$result = parser.getSymbolFactory().newSymbol("copy",1, ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-3)), ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.peek()), RESULT);
            }
          return CUP$ParserFileCopy$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // copyp ::= copyp PROYECT1 DOSPUNTOS STRING COMA 
            {
              FileCopy RESULT =null;
		int coppleft = ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-4)).left;
		int coppright = ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-4)).right;
		FileCopy copp = (FileCopy)((java_cup.runtime.Symbol) CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-4)).value;
		int strleft = ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-1)).left;
		int strright = ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-1)).right;
		Object str = (Object)((java_cup.runtime.Symbol) CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-1)).value;
		
                                                                RESULT = copp;
                                                                if(RESULT != null){
                                                                    Token token = (Token) str;
                                                                    if(RESULT.getPathProyecto1()!=null){
                                                                        System.out.println("La propeidad JSON ya estaba definida");
                                                                    }else{
                                                                        if(token.getLexema().isEmpty() || token.getLexema().isBlank()){
                                                                            System.out.println("La cadena de asigancion esta vacia");
                                                                        }else{
                                                                            RESULT.setPathProyecto1(token.getLexema());
                                                                        }
                                                                    }
                                                                }
                                                            
              CUP$ParserFileCopy$result = parser.getSymbolFactory().newSymbol("copyp",2, ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-4)), ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.peek()), RESULT);
            }
          return CUP$ParserFileCopy$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // copyp ::= copyp PROYECT2 DOSPUNTOS STRING COMA 
            {
              FileCopy RESULT =null;
		int coppleft = ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-4)).left;
		int coppright = ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-4)).right;
		FileCopy copp = (FileCopy)((java_cup.runtime.Symbol) CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-4)).value;
		int strleft = ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-1)).left;
		int strright = ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-1)).right;
		Object str = (Object)((java_cup.runtime.Symbol) CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-1)).value;
		
                                                                RESULT = copp;
                                                                if(RESULT != null){
                                                                    Token token = (Token) str;
                                                                    if(RESULT.getPathProyecto2()!=null){
                                                                        System.out.println("La propeidad JSON ya estaba definida");
                                                                    }else{
                                                                        if(token.getLexema().isEmpty() || token.getLexema().isBlank()){
                                                                            System.out.println("La cadena de asigancion esta vacia");
                                                                        }else{
                                                                            RESULT.setPathProyecto2(token.getLexema());
                                                                        }
                                                                    }
                                                                }
                                                            
              CUP$ParserFileCopy$result = parser.getSymbolFactory().newSymbol("copyp",2, ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-4)), ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.peek()), RESULT);
            }
          return CUP$ParserFileCopy$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // copyp ::= copyp FILEDEF DOSPUNTOS STRING COMA 
            {
              FileCopy RESULT =null;
		int coppleft = ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-4)).left;
		int coppright = ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-4)).right;
		FileCopy copp = (FileCopy)((java_cup.runtime.Symbol) CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-4)).value;
		int strleft = ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-1)).left;
		int strright = ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-1)).right;
		Object str = (Object)((java_cup.runtime.Symbol) CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-1)).value;
		
                                                                RESULT = copp;
                                                                if(RESULT != null){
                                                                    Token token = (Token) str;
                                                                    if(RESULT.getPathFileDef()!=null){
                                                                        System.out.println("La propeidad JSON ya estaba definida");
                                                                    }else{
                                                                        if(token.getLexema().isEmpty() || token.getLexema().isBlank()){
                                                                            System.out.println("La cadena de asigancion esta vacia");
                                                                        }else{
                                                                            RESULT.setPathFileDef(token.getLexema());
                                                                        }
                                                                    }
                                                                }
                                                            
              CUP$ParserFileCopy$result = parser.getSymbolFactory().newSymbol("copyp",2, ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-4)), ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.peek()), RESULT);
            }
          return CUP$ParserFileCopy$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // copyp ::= copyp REPORTJSON DOSPUNTOS STRING COMA 
            {
              FileCopy RESULT =null;
		int coppleft = ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-4)).left;
		int coppright = ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-4)).right;
		FileCopy copp = (FileCopy)((java_cup.runtime.Symbol) CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-4)).value;
		int strleft = ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-1)).left;
		int strright = ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-1)).right;
		Object str = (Object)((java_cup.runtime.Symbol) CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-1)).value;
		
                                                                RESULT = copp;
                                                                if(RESULT != null){
                                                                    Token token = (Token) str;
                                                                    if(RESULT.getPathFileReporteJson()!=null){
                                                                        System.out.println("La propeidad JSON ya estaba definida");
                                                                    }else{
                                                                        if(token.getLexema().isEmpty() || token.getLexema().isBlank()){
                                                                            System.out.println("La cadena de asigancion esta vacia");
                                                                        }else{
                                                                            RESULT.setPathFileReporteJson(token.getLexema());
                                                                        }
                                                                    }
                                                                }
                                                            
              CUP$ParserFileCopy$result = parser.getSymbolFactory().newSymbol("copyp",2, ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.elementAt(CUP$ParserFileCopy$top-4)), ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.peek()), RESULT);
            }
          return CUP$ParserFileCopy$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // copyp ::= 
            {
              FileCopy RESULT =null;
		
                RESULT= new FileCopy();
            
              CUP$ParserFileCopy$result = parser.getSymbolFactory().newSymbol("copyp",2, ((java_cup.runtime.Symbol)CUP$ParserFileCopy$stack.peek()), RESULT);
            }
          return CUP$ParserFileCopy$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ParserFileCopy$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ParserFileCopy$do_action(
    int                        CUP$ParserFileCopy$act_num,
    java_cup.runtime.lr_parser CUP$ParserFileCopy$parser,
    java.util.Stack            CUP$ParserFileCopy$stack,
    int                        CUP$ParserFileCopy$top)
    throws java.lang.Exception
    {
              return CUP$ParserFileCopy$do_action_part00000000(
                               CUP$ParserFileCopy$act_num,
                               CUP$ParserFileCopy$parser,
                               CUP$ParserFileCopy$stack,
                               CUP$ParserFileCopy$top);
    }
}

}
