
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.cresb49.appcliente.analizadores.filecopy;

/** CUP generated class containing symbol constants. */
public class ParserFileCopySym {
  /* terminals */
  public static final int COMA = 4;
  public static final int DOSPUNTOS = 5;
  public static final int FILEDEF = 9;
  public static final int EOF = 0;
  public static final int STRING = 6;
  public static final int PROYECT2 = 8;
  public static final int error = 1;
  public static final int PROYECT1 = 7;
  public static final int LLA_C = 3;
  public static final int REPORTJSON = 10;
  public static final int LLA_A = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LLA_A",
  "LLA_C",
  "COMA",
  "DOSPUNTOS",
  "STRING",
  "PROYECT1",
  "PROYECT2",
  "FILEDEF",
  "REPORTJSON"
  };
}

